### ISSUE TITLE
It cannot create any pack with create pack command

### ISSUE THREAD

**Issue by HelloC** [MrLuje/vscode-extensions-pack-builder#25]
![image](https://user-images.githubusercontent.com/3824645/90332497-fd6a4780-dfef-11ea-87fe-d8f949c42d53.png)

**Comment by HelloC** [comment]
I have installed vscode-extensions-pack-builder extension in the
vscode  v1.52.0 windows 10. But when create a new pack, a pop view show
that one was building, and a fiew later, it could not be installed
No pack was found in the extension side bar of vscode

**Comment by pinage404** [comment]
I didn't used this extension since a while ; when i used it, it was working fine

---

I've just reinstalled it to retest it, then i did : 
* open the command palette
* select "Extensions Pack: Create pack"
* enter a name "my-extensions-pack"
* select few extentions then valid

Then it does exactly what you described

---

I've opened VSCode in a terminal using `code --verbose` to be able to watch the errors

There is this errors when i tryied to create an extensions pack

```
[9770:1213/164433.005978:INFO:CONSOLE(3129)] "Failed to generate the pack...", source: file:///nix/store/bnc90yma5v8j64nyvp1886bhb2ka0g7c-vscode-1.51.1/lib/vscode/resources/app/out/vs/workbench/workbench.desktop.main.js (3129)
```

---

I have this version

```
code --list-extensions --show-versions | grep "mrluje.vscode-extensions-pack-builder"
mrluje.vscode-extensions-pack-builder@0.1.5
```

I have this VSCode's version

```
Version : 1.51.1
Commit : e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date : 2020-11-10T23:31:29.624Z
Electron : 9.3.3
Chrome : 83.0.4103.122
Node.js : 12.14.1
V8 : 8.3.110.13-electron.0
OS : Linux x64 5.4.81
```

**Comment by MrLuje** [comment]
Sorry, mistake on my side... it was not properly working anymore for new install
A file was missing in the build process. 

Fix is available in latest version
